### ISSUE TITLE
关于出现 AiProtection 警告页面

### ISSUE THREAD

**Issue by xi4oh4o** [GaryFan/smallbeex#3]
你好，
smallbeex 2.9.0 访问部分网址会弹出 /blocking.asp?cat_id=86 ，Trend AiProtection警告页面，该设置页面被精简了，请问如何彻底关闭？

**Comment by GaryFan** [comment]
如果方便请提供下访问的网址，我这边测试下，如有问题会尽快fix。

**Comment by xi4oh4o** [comment]
最近一次遇到是 https://www.ke.com 提示的，在刷smallbeex之前，是官方固件，确定是把相关AirProtection都关闭的
